[1]
template = """
>模板
“峰回路转，雾凇乍现，一缕阳光斜射，刹那间晶莹剔透，宛若仙境，美极了！ #风景 #旅行”\n“秋是慢入的,但冷却是突然的,晴不知夏去,一雨方觉秋深！有些情绪不言而喻…… #最美风景 #秋天 #心动的旅行”\n“愿新年胜旧年，愿将来胜过往，愿你与旧事归于尽，来年依旧迎花开。#向烟花许个愿 #除夕 #大年三十 #跨年夜”\n“你是我最想留住的幸运，我想用我的心，把你永远留在我身边。#情话 #表白 #爱情”\n“被人艾特看烟花是一件很浪漫的事情吧”\n“被你艾特的人 会陪你很久很久”\n“分享欲是最高级的浪漫”

>仿写
图像标签为{tags}
你需要仿写相同风格的文本。
"""

[2]
template = """
>案例模板
"我的衣服老是被我弄破，于是我报了一个补衣服的班。有一天老师教我们大家缝衣服，他问道“谁的衣服总是弄坏”，于是我高高举起手向{name}姐姐大喊：“我的老破我的老破。”",
"{name}，今天我看到一个女孩很像你，我发了疯似的跑出去，可突然想起这座城市根本没有你，我愣了，放慢了脚步，也放下了手里的麻袋和电枪……",
"{name}姐姐你终于发消息了，你知道吗？昨天下午我被人骂了，他们说我往楼下滴水，把阳台上晾的衣服都打湿了，只有我知道那不是水，是我趴在阳台上想你流的眼泪",
"{name}姐姐知不知道， 你生气的时候， 跟偶尔开心笑起来的时候一模一样， 都有两个小酒窝， 我最喜欢你这点了， 所以你迟些动手杀我， 我好多看几眼。​",

>仿写任务
肖像标签为{tags}
仿照模板内容，你需要写一段痴狂的情话。
"""

[3]
template = "整理一下我的{tags}，希望你喜欢！"
