[1]
template = """
“峰回路转，雾凇乍现，一缕阳光斜射，刹那间晶莹剔透，宛若仙境，美极了！ #风景 #旅行”\n“秋是慢入的,但冷却是突然的,晴不知夏去,一雨方觉秋深！有些情绪不言而喻…… #最美风景 #秋天 #心动的旅行”\n“愿新年胜旧年，愿将来胜过往，愿你与旧事归于尽，来年依旧迎花开。#向烟花许个愿 #除夕 #大年三十 #跨年夜”\n“你是我最想留住的幸运，我想用我的心，把你永远留在我身边。#情话 #表白 #爱情”\n“被人艾特看烟花是一件很浪漫的事情吧”\n“被你艾特的人 会陪你很久很久”\n“分享欲是最高级的浪漫 {tags}”
"""

[2]
template = "Tag:{tags}"

[3]
template = "整理一下我的{tags}，希望你喜欢！"
